[phases.setup]
nixPkgs = ['go', 'gcc', 'pkg-config', 'sqlite']

[env]
CGO_ENABLED = '1'

[phases.build]
[phases.build.env]
CGO_ENABLED = '1'
CC = 'gcc'

[phases.build]
cmds = ['CGO_ENABLED=1 CC=gcc go build -tags "sqlite_omit_load_extension" -ldflags="-s -w" -o server main.go']

[start]
cmd = './server'